using System.Threading;
using System.Threading.Tasks;

namespace EverscaleNet.Testing;

/// <summary>
///     Main
/// </summary>
public interface IContract {
	/// <summary>
	///     Contract address, should be generated by .ctor or InitByPublicKey
	/// </summary>
	string Address { get; }

	/// <summary>
	///     Returns contract balance in coins
	/// </summary>
	/// <param name="cancellationToken"></param>
	/// <returns>Decimal balance</returns>
	Task<decimal> GetBalance(CancellationToken cancellationToken = default);

	/// <summary>
	///     Generate address by public key and tvc
	/// </summary>
	/// <param name="publicKey"></param>
	/// <param name="cancellationToken"></param>
	Task InitByPublicKey(string publicKey, CancellationToken cancellationToken = default);
}
