name: 'CI'

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

env:
  DOTNET_NOLOGO: true
  NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
  SolCompilerVersion: 0.71.0

jobs:
  labels:
    name: Label taking off
    if: github.event.label.name == 'publish'
    runs-on: ubuntu-latest
    steps:
      - name: Take off label
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: >
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: '${{ github.event.label.name }}'
            })
  
  build:
    name: Build, test and pack
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run Node SE
        run: docker run -d --name tonlab-node -e USER_AGREEMENT=yes -p5555:80 tonlabs/local-node

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('Directory.Packages.props') }}
          restore-keys: |
            nuget-

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x

      - name: Restore
        run: dotnet restore -v normal

      - name: Build
        run: dotnet build -c Release --no-restore -v normal -ds -m

      - name: Wait for first block of Node SE
        timeout-minutes: 5
        run: |
          while true; do
            firstBlockId=`curl --max-time 1 -s 'http://localhost:5555/graphql' --header 'Content-Type: application/json' --data '{"query":"{ blocks(limit: 1) { id }}"}' | jq -r -e '.data.blocks[0].id?'`
            if [[ ! -z "$firstBlockId" ]]; then
              break
            fi
            sleep 1
          done

      - name: Test
        timeout-minutes: 10
        env:
          EVERSCALE_NETWORK_ENDPOINTS: http://localhost:5555
        run: |
          dotnet test --no-build -c Release --logger "console;verbosity=normal" --logger "trx;LogFilePrefix=results" -m

      - name: Upload test results trx files
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: '**/*.trx'

      - name: Pack and publish Release package
        if: github.event_name == 'release'
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]//v}"
          echo Publish package version: $VERSION
          dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION -p:RunNumber=${{ github.run_number }}
          dotnet nuget push "src/**/bin/Release/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate
          dotnet nuget push "src/**/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_KEY --skip-duplicate

      - name: Pack and publish PR package
        if: github.event.label.name == 'publish'
        run: |
          VERSION=${{ github.event.number }}.${{ github.run_number }}
          dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION
          dotnet nuget push "src/**/bin/Release/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ github.token }} --skip-duplicate
